apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ tpl .Values.resource.default.name  . }}
  namespace: {{ tpl .Values.resource.default.namespace . }}
  labels:
    app: {{ .Values.project.name }}
    giantswarm.io/service-type: "managed"
