apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.project.name }}
  namespace: {{ .Values.project.namespace }}
  labels:
    app: {{ .Values.project.name }}
    giantswarm.io/service-type: "managed"
