apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: {{ .Values.project.name }}
  labels:
    app: {{ .Values.project.name }}
    giantswarm.io/service-type: "managed"
rules:
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - "*"
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions/status
  verbs:
  - create
  - patch
  - update
- apiGroups:
  - application.giantswarm.io
  resources:
  - charts
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - application.giantswarm.io
  resources:
  - charts/status
  verbs:
  - create
  - patch
  - update
- apiGroups:
  - core.giantswarm.io
  resources:
  - chartconfigs
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - core.giantswarm.io
  resources:
  - chartconfigs/status
  verbs:
  - create
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - "get"
  - "list"
- apiGroups:
  - ""
  resources:
  - configmaps
  - secrets
  verbs:
  - "get"
- apiGroups:
  - ""
  resources:
  - pods/portforward
  verbs:
  - "create"
- apiGroups:
  - "rbac.authorization.k8s.io"
  resources:
  - clusterrolebindings
  verbs:
  - "create"
- apiGroups:
  - "rbac.authorization.k8s.io"
  resources:
  - clusterroles
  verbs:
  - "bind"
- apiGroups:
  - ""
  resources:
  - services
  - serviceaccounts
  verbs:
  - "create"
- apiGroups:
  - networking.k8s.io
  resources:
  - networkpolicies
  verbs:
  - create
- apiGroups:
  - extensions
  resources:
  - deployments
  verbs:
  - "create"
  - "get"
  - "update"
- nonResourceURLs:
  - "/"
  - "/healthz"
  verbs:
    - get
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.project.name }}
  labels:
    app: {{ .Values.project.name }}
    giantswarm.io/service-type: "managed"
subjects:
  - kind: ServiceAccount
    name: {{ .Values.project.name }}
    namespace: {{ .Values.project.namespace }}
roleRef:
  kind: ClusterRole
  name: {{ .Values.project.name }}
  apiGroup: rbac.authorization.k8s.io
