apiVersion: v1
kind: Service
metadata:
  name: {{ tpl .Values.resource.default.name  . }}
  namespace: {{ .Values.resource.default.namespace }}
  labels:
    app: {{ .Values.project.name }}
    giantswarm.io/service-type: "managed"
  annotations:
    prometheus.io/scrape: "true"
spec:
  ports:
  - port: {{ .Values.pod.port }}
  selector:
    app: {{ .Values.project.name }}
