apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ tpl .Values.resource.default.name  . }}
  namespace: {{ tpl .Values.resource.default.namespace . }}
  labels:
    app: {{ .Values.project.name }}
    giantswarm.io/service-type: "managed"
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: {{ .Values.project.name }}
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ .Values.project.name }}
        giantswarm.io/service-type: "managed"
      annotations:
        releaseRevision: {{ $.Release.Revision }}
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            preference:
              matchExpressions:
              - key: role
                operator: In
                values:
                - master
      volumes:
      - name: {{ .Values.project.name }}
        configMap:
          name: {{ .Values.project.name }}
          items:
          - key: config.yaml
            path: config.yaml
      priorityClassName: giantswarm-critical
      serviceAccountName: {{ tpl .Values.resource.default.name  . }}
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      dnsPolicy: None
      dnsConfig:
        nameservers:
        - {{ .Values.clusterDNSIP }}
        {{- range (splitList "," .Values.externalDNSIP) }}
        - {{ . }}
        {{- end }}
        searches:
        - giantswarm.svc.{{ .Values.cluster.kubernetes.domain }}
        - svc.{{ .Values.cluster.kubernetes.domain }}
        - {{ .Values.cluster.kubernetes.domain }}
        options:
        - name: ndots
          value: "5"
      initContainers:
      - name: wait-for-quay
        {{ if (.Values.Installation) }}
        image: "{{ .Values.Installation.V1.Registry.Domain }}/{{ .Values.image.name }}:{{ .Values.image.tag }}"
        {{ else }}
        image: "{{ .Values.image.registry }}/{{ .Values.image.name }}:{{ .Values.image.tag }}"
        {{ end }}
        command: 
        - sh
        - -c
        - until dig quay.io. {{ range (splitList "," .Values.externalDNSIP) }}@{{ . }} {{ end }}; do echo waiting for quay.io; sleep 2; done;
        securityContext:
          runAsUser: {{ .Values.pod.user.id }}
          runAsGroup: {{ .Values.pod.group.id }}
      containers:
      - name: {{ .Values.project.name }}
        {{ if (.Values.Installation) }}
        image: "{{ .Values.Installation.V1.Registry.Domain }}/{{ .Values.image.name }}:{{ .Values.image.tag }}"
        {{ else }}
        image: "{{ .Values.image.registry }}/{{ .Values.image.name }}:{{ .Values.image.tag }}"
        {{ end }}
        volumeMounts:
        - name: {{  .Values.project.name }}
          mountPath: /var/run/{{ .Values.project.name }}/configmap/
        ports:
        - name: http
          containerPort: {{ .Values.pod.port }}
        args:
        - daemon
        - --config.dirs=/var/run/{{ .Values.project.name }}/configmap/
        - --config.files=config
        securityContext:
          runAsUser: {{ .Values.pod.user.id }}
          runAsGroup: {{ .Values.pod.group.id }}
        livenessProbe:
          httpGet:
            path: /healthz
            port: {{ .Values.pod.port }}
          initialDelaySeconds: 15
          timeoutSeconds: 1
        readinessProbe:
          httpGet:
            path: /healthz
            port: {{ .Values.pod.port }}
          initialDelaySeconds: 15
          timeoutSeconds: 1
        resources:
          requests:
            cpu: 250m
            memory: 250Mi
          limits:
            memory: 250Mi
