kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: {{ tpl .Values.resource.default.name  . }}
  namespace: {{ tpl .Values.resource.default.namespace . }}
  labels:
    {{- include "chart-operator.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      app: {{ .Values.project.name }}
  ingress:
  - ports:
    - port: {{ .Values.pod.port }}
      protocol: TCP
  egress:
  - {}
  policyTypes:
  - Egress
  - Ingress
