apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: {{ tpl .Values.resource.psp.name . }}
  labels:
    app: {{ .Values.project.name }}
    giantswarm.io/service-type: "managed"
spec:
  runAsUser:
    rule: MustRunAsNonRoot
  runAsGroup:
    rule: MustRunAs
    ranges:
      - min: 1
        max: 65535
  fsGroup:
    rule: MustRunAs
    ranges:
      - min: 1
        max: 65535
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  volumes:
    - 'configMap'
    - 'secret'
  allowPrivilegeEscalation: false
  hostNetwork: false
  hostIPC: false
  hostPID: false
