apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ tpl .Values.resource.default.name  . }}
  labels:
    app: {{ .Values.project.name }}
    giantswarm.io/service-type: "managed"
rules:
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - "*"
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions/status
  verbs:
  - create
  - patch
  - update
- apiGroups:
  - application.giantswarm.io
  resources:
  - charts
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - application.giantswarm.io
  resources:
  - charts/status
  verbs:
  - create
  - patch
  - update
- apiGroups:
  - core.giantswarm.io
  resources:
  - chartconfigs
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - core.giantswarm.io
  resources:
  - chartconfigs/status
  verbs:
  - create
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - "get"
  - "list"
- apiGroups:
  - ""
  resources:
  - configmaps
  - secrets
  verbs:
  - "get"
  - "list"
- apiGroups:
  - ""
  resources:
  - pods/portforward
  verbs:
  - "create"
- apiGroups:
  - "rbac.authorization.k8s.io"
  resources:
  - clusterrolebindings
  verbs:
  - "create"
- apiGroups:
  - "rbac.authorization.k8s.io"
  resources:
  - clusterroles
  verbs:
  - "bind"
  - "create"
  - "delete"
- apiGroups:
  - ""
  resources:
  - services
  - serviceaccounts
  verbs:
  - "create"
  - "delete"
  - "get"
- apiGroups:
  - networking.k8s.io
  resources:
  - networkpolicies
  verbs:
  - create
  - delete
- apiGroups:
  - scheduling.k8s.io
  resources:
  - priorityclasses
  verbs:
  - create
  - delete
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - "create"
  - "delete"
  - "get"
  - "update"
- apiGroups:
  - extensions
  resources:
  - deployments
  verbs:
  - "create"
  - "delete"
  - "get"
  - "update"
- apiGroups:
  - policy
  resources:
  - podsecuritypolicies
  verbs:
  - "create"
  - "delete"
  - "use"
- nonResourceURLs:
  - "/"
  - "/healthz"
  verbs:
    - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ tpl .Values.resource.default.name  . }}
  labels:
    app: {{ .Values.project.name }}
    giantswarm.io/service-type: "managed"
subjects:
  - kind: ServiceAccount
    name: {{ tpl .Values.resource.default.name  . }}
    namespace: {{ tpl .Values.resource.default.namespace . }}
roleRef:
  kind: ClusterRole
  name: {{ tpl .Values.resource.default.name  . }}
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ tpl .Values.resource.psp.name . }}
  labels:
    app: {{ .Values.project.name }}
    giantswarm.io/service-type: "managed"
rules:
  - apiGroups:
      - extensions
    resources:
      - podsecuritypolicies
    resourceNames:
      - {{ tpl .Values.resource.psp.name . }}
    verbs:
      - use
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ tpl .Values.resource.psp.name . }}-user
  labels:
    app: {{ .Values.project.name }}
    giantswarm.io/service-type: "managed"
subjects:
  - kind: ServiceAccount
    name: {{ tpl .Values.resource.default.name  . }}
    namespace: {{ tpl .Values.resource.default.namespace . }}
roleRef:
  kind: ClusterRole
  name: {{ tpl .Values.resource.psp.name . }}
  apiGroup: rbac.authorization.k8s.io
