apiVersion: "core.giantswarm.io/v1alpha1"
kind: ChartConfig
metadata:
  name: "{{ .Values.chart.name }}"
  namespace: "{{ .Values.namespace }}"
spec:
  chart:
    channel: "{{ .Values.chart.channel }}"
    name: "{{ .Values.chart.name }}"
    namespace: "{{ .Values.chart.namespace }}"
    release: "{{ .Values.chart.release }}"
  versionBundle:
    version: "{{ .Values.versionBundleVersion }}"
