version: 2.1
orbs:
  architect: giantswarm/architect@0.8.6

workflows:
  build:
    jobs:

      - architect/go-build:
          name: go-build
          binary: chart-operator
          filters:
            tags:
              only: /^v.*/

      - architect/push-to-docker:
          name: push-chart-operator-to-quay
          image: "quay.io/giantswarm/chart-operator"
          username_envar: "QUAY_USERNAME"
          password_envar: "QUAY_PASSWORD"
          requires:
            - go-build
          # Needed to trigger job also on git tag.
          filters:
            tags:
              only: /^v.*/

      - architect/push-to-docker:
          name: push-chart-operator-to-aliyun
          image: "registry-intl.cn-shanghai.aliyuncs.com/giantswarm/chart-operator"
          username_envar: "ALIYUN_USERNAME"
          password_envar: "ALIYUN_PASSWORD"
          requires:
            - go-build
          # Needed to trigger job only on git tag.
          filters:
            branches:
              only: master
            tags:
              only: /^v.*/

      - architect/push-to-app-catalog:
          name: push-chart-operator-to-control-plane-app-catalog
          app_catalog: "control-plane-catalog"
          app_catalog_test: "control-plane-test-catalog"
          chart: "chart-operator"
          requires:
            - push-chart-operator-to-quay
          filters:
            tags:
              only: /^v.*/

      - architect/push-to-app-catalog:
          name: push-chart-operator-to-app-catalog
          app_catalog: "default-catalog"
          app_catalog_test: "default-test-catalog"
          chart: "chart-operator"
          requires:
            - push-chart-operator-to-quay
          filters:
            # Needed to trigger job also on git tag.
            tags:
              only: /^v.*/

      - architect/integration-test:
          name: basic-integration-test
          test-dir: "integration/test/chart/basic"
          requires:
          - go-build
      
      - architect/integration-test:
          name: migration-integration-test
          test-dir: "integration/test/chart/migration"
          requires:
          - go-build
