version: 2.1
orbs:
  architect: giantswarm/architect@0.8.3

jobs:
  deploy:
    machine: true
    steps:
    - checkout

    - attach_workspace:
        at: .

    - run: ./architect deploy

    - run:
        name: publish to beta
        command: ./architect publish
    - run: |
        sed -i 's/version:.*/version: 1.0.0-'"${CIRCLE_SHA1}"'/' helm/chart-operator-chart/Chart.yaml
        ./architect publish

  publish_to_stable:
    machine: true
    steps:
    - checkout

    - attach_workspace:
        at: .

    - run: ./architect publish --stable

workflows:
  build:
    jobs:
      - architect/go-build:
          name: go-build-chart-operator
          binary: chart-operator
          filters:
            # Needed to trigger job also on git tag.
            tags:
              only: /^v.*/

      - architect/push-to-docker:
          name: push-chart-operator-to-quay
          image: "quay.io/giantswarm/chart-operator"
          username_envar: "QUAY_USERNAME"
          password_envar: "QUAY_PASSWORD"
          requires:
            - go-build-chart-operator
          # Needed to trigger job also on git tag.
          filters:
            tags:
              only: /^v.*/

      - architect/push-to-docker:
          name: push-chart-operator-to-aliyun
          image: "registry-intl.cn-shanghai.aliyuncs.com/giantswarm/chart-operator"
          username_envar: "ALIYUN_USERNAME"
          password_envar: "ALIYUN_PASSWORD"
          requires:
            - go-build-chart-operator
          # Needed to trigger job only on git tag.
          filters:
            branches:
              only: master
            tags:
              only: /^v.*/

      - architect/push-to-docker-legacy:
          name: push-chart-operator-to-aliyun-legacy
          image: "registry-intl.cn-shanghai.aliyuncs.com/giantswarm/chart-operator"
          username_envar: "ALIYUN_USERNAME"
          password_envar: "ALIYUN_PASSWORD"
          requires:
            - go-build-chart-operator

      - architect/push-to-app-catalog:
          name: push-chart-operator-to-app-catalog
          app_catalog: "default-catalog"
          app_catalog_test: "default-test-catalog"
          chart: "chart-operator"
          requires:
            - push-chart-operator-to-quay
          filters:
            # Needed to trigger job also on git tag.
            tags:
              only: /^v.*/

      - architect/integration-test:
          name: basic-integration-test
          test-dir: "integration/test/chart/basic"
          requires:
          - go-build-chart-operator
      
      - architect/integration-test:
          name: migration-integration-test
          test-dir: "integration/test/chart/migration"
          requires:
          - go-build-chart-operator

      - deploy:
          filters:
            branches:
              only: master
          requires:
          - push-chart-operator-to-aliyun-legacy

      - publish_to_stable:
          filters:
            branches:
              only: master
          requires:
          - deploy
