e2eTest: &e2eTest
    machine: true
    working_directory: /home/circleci/.go_workspace/src/github.com/giantswarm/chart-operator
    steps:
    - checkout

    - attach_workspace:
        at: .

    - run: |
        wget -q $(curl -sS https://api.github.com/repos/giantswarm/e2e-harness/releases/latest | grep browser_download_url | head -n 1 | cut -d '"' -f 4)
        chmod +x ./e2e-harness

    - run: ./e2e-harness localkube

    - run: ./e2e-harness setup --remote=false

    - run: ./e2e-harness test --test-dir=${TEST_DIR}

    - run:
        name: Finish with cleanup, no matter if the test succeeded or not
        command: ./e2e-harness teardown
        when: always

version: 2
jobs:
  build:
    machine: true
    steps:
    - checkout

    - run: |
        wget -q $(curl -sS -H "Authorization: token $RELEASE_TOKEN" https://api.github.com/repos/giantswarm/architect/releases/latest | grep browser_download_url | head -n 1 | cut -d '"' -f 4)
        chmod +x ./architect
        ./architect version
    - run: ./architect build
    - run: ./architect publish --pipeline=false --channels=${CIRCLE_SHA1}
    - persist_to_workspace:
        root: .
        paths:
        - ./chart-operator
        - ./architect

  e2eTestCurBasicPR:
    environment:
      TEST_DIR: "integration/test/basic"
      TESTED_VERSION: "current"
    <<: *e2eTest

  e2eTestCurBasicMaster:
    environment:
      TEST_DIR: "integration/test/basic"
      TESTED_VERSION: "current"
    <<: *e2eTest

  e2eTestWIPBasicPR:
    environment:
      TEST_DIR: "integration/test/basic"
      TESTED_VERSION: "wip"
    <<: *e2eTest

  e2eTestWIPBasicMaster:
    environment:
      TEST_DIR: "integration/test/basic"
      TESTED_VERSION: "wip"
    <<: *e2eTest

  e2eTestCurChartValuesPR:
    environment:
      TEST_DIR: "integration/test/chartvalues"
      TESTED_VERSION: "current"
    <<: *e2eTest

  e2eTestCurChartValuesMaster:
    environment:
      TEST_DIR: "integration/test/chartvalues"
      TESTED_VERSION: "current"
    <<: *e2eTest

  e2eTestWIPChartValuesPR:
    environment:
      TEST_DIR: "integration/test/chartvalues"
      TESTED_VERSION: "wip"
    <<: *e2eTest

  e2eTestWIPChartValuesMaster:
    environment:
      TEST_DIR: "integration/test/chartvalues"
      TESTED_VERSION: "wip"
    <<: *e2eTest

  deploy:
    machine: true
    steps:
    - checkout

    - attach_workspace:
        at: .

    - run: ./architect deploy

    - run:
        name: publish to beta
        command: ./architect publish

  publish_to_stable:
    machine: true
    steps:
    - checkout

    - attach_workspace:
        at: .

    - run: ./architect publish --stable

workflows:
  version: 2
  build_e2e:
    jobs:
      - build

      - e2eTestCurBasicPR:
          requires:
          - build

      - e2eTestCurBasicMaster:
          filters:
            branches:
              only: master
          requires:
          - build

      - e2eTestWIPBasicPR:
          requires:
          - build

      - e2eTestWIPBasicMaster:
          filters:
            branches:
              only: master
          requires:
          - build

      - e2eTestCurChartValuesPR:
          requires:
          - build

      - e2eTestCurChartValuesMaster:
          filters:
            branches:
              only: master
          requires:
          - build

      - e2eTestWIPChartValuesPR:
          requires:
          - build

      - e2eTestWIPChartValuesMaster:
          filters:
            branches:
              only: master
          requires:
          - build

      - deploy:
          filters:
            branches:
              only: master
          requires:
          - e2eTestCurBasicMaster
          - e2eTestWIPBasicMaster
          - e2eTestCurChartValuesMaster
          - e2eTestWIPChartValuesMaster

      - publish_to_stable:
          filters:
            branches:
              only: master
          requires:
          - deploy
