apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
data:
  config.yaml: |
    server:
      listen:
        address: 'http://0.0.0.0:{{ .Values.port }}'
    service:
      cnr:
        address: '{{ .Values.cnr.address }}'
      kubernetes:
        incluster: true
        watch:
          namespace: 'kube-system'
