apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
data:
  config.yaml: |
    server:
      listen:
        address: 'http://0.0.0.0:{{ .Values.port }}'
      kubernetes:
        incluster: true
    service:
      cnr:
        address: 'https://quay.io'
