apiVersion: v1
appVersion: "[[ .AppVersion ]]"
name: chart-operator
description: "chart-operator is an agent for deploying Helm charts as releases."
home: https://github.com/giantswarm/chart-operator
version: [[ .Version ]]
