image:
  registry: "quay.io"
  repository: "giantswarm/chart-operator"
  tag: "[[ .Version ]]"
pod:
  user:
    id: 1000
  group:
    id: 1000
  port: 8000
  replicas: 1
project:
  name: "chart-operator"
resource:
  clusterDNSIP: 172.31.0.10
  cnr:
    address: https://quay.io
  default:
    name:  chart-operator-v[[ .Version | replace "." "-" ]]
    namespace: "giantswarm"
  psp:
    name: chart-operator-psp-v[[ .Version | replace "." "-" ]]
  pullSecret:
    name: chart-operator-pull-secret-v[[ .Version | replace "." "-" ]]
    namespace: "giantswarm"
  tiller:
    namespace: "kube-system"
